// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: billno.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetBillnoReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetBillnoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBillnoReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetBillnoReqMultiError, or
// nil if none found.
func (m *GetBillnoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBillnoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBizCode()) < 1 {
		err := GetBillnoReqValidationError{
			field:  "BizCode",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetBillnoReqMultiError(errors)
	}

	return nil
}

// GetBillnoReqMultiError is an error wrapping multiple validation errors
// returned by GetBillnoReq.ValidateAll() if the designated constraints aren't met.
type GetBillnoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBillnoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBillnoReqMultiError) AllErrors() []error { return m }

// GetBillnoReqValidationError is the validation error returned by
// GetBillnoReq.Validate if the designated constraints aren't met.
type GetBillnoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBillnoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBillnoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBillnoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBillnoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBillnoReqValidationError) ErrorName() string { return "GetBillnoReqValidationError" }

// Error satisfies the builtin error interface
func (e GetBillnoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBillnoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBillnoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBillnoReqValidationError{}

// Validate checks the field values on GetBillnoResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetBillnoResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBillnoResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetBillnoRespMultiError, or
// nil if none found.
func (m *GetBillnoResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBillnoResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Billno

	if len(errors) > 0 {
		return GetBillnoRespMultiError(errors)
	}

	return nil
}

// GetBillnoRespMultiError is an error wrapping multiple validation errors
// returned by GetBillnoResp.ValidateAll() if the designated constraints
// aren't met.
type GetBillnoRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBillnoRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBillnoRespMultiError) AllErrors() []error { return m }

// GetBillnoRespValidationError is the validation error returned by
// GetBillnoResp.Validate if the designated constraints aren't met.
type GetBillnoRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBillnoRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBillnoRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBillnoRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBillnoRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBillnoRespValidationError) ErrorName() string { return "GetBillnoRespValidationError" }

// Error satisfies the builtin error interface
func (e GetBillnoRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBillnoResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBillnoRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBillnoRespValidationError{}
