// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billno.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.billno;

public final class BillnoOuterClass {
  private BillnoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_billno_GetBillnoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_billno_GetBillnoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_billno_GetBillnoResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_billno_GetBillnoResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014billno.proto\022\022com.seezoon.billno\032\027vali" +
      "date/validate.proto\")\n\014GetBillnoReq\022\031\n\010b" +
      "iz_code\030\001 \001(\tB\007\372B\004r\002\020\001\"\037\n\rGetBillnoResp\022" +
      "\016\n\006billno\030\001 \001(\0042\\\n\006Billno\022R\n\tGetBillno\022 " +
      ".com.seezoon.billno.GetBillnoReq\032!.com.s" +
      "eezoon.billno.GetBillnoResp\"\000BM\n\027com.see" +
      "zoon.stub.billnoP\001Z0github.com/seezoon-g" +
      "o-stub/billno-server-stub;pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
        });
    internal_static_com_seezoon_billno_GetBillnoReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_seezoon_billno_GetBillnoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_billno_GetBillnoReq_descriptor,
        new java.lang.String[] { "BizCode", });
    internal_static_com_seezoon_billno_GetBillnoResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_seezoon_billno_GetBillnoResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_billno_GetBillnoResp_descriptor,
        new java.lang.String[] { "Billno", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
