// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billno.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.billno;

/**
 * Protobuf type {@code com.seezoon.billno.GetBillnoResp}
 */
public final class GetBillnoResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.seezoon.billno.GetBillnoResp)
    GetBillnoRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetBillnoResp.newBuilder() to construct.
  private GetBillnoResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetBillnoResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetBillnoResp();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.seezoon.stub.billno.BillnoOuterClass.internal_static_com_seezoon_billno_GetBillnoResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.seezoon.stub.billno.BillnoOuterClass.internal_static_com_seezoon_billno_GetBillnoResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.seezoon.stub.billno.GetBillnoResp.class, com.seezoon.stub.billno.GetBillnoResp.Builder.class);
  }

  public static final int BILLNO_FIELD_NUMBER = 1;
  private long billno_ = 0L;
  /**
   * <code>uint64 billno = 1;</code>
   * @return The billno.
   */
  @java.lang.Override
  public long getBillno() {
    return billno_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (billno_ != 0L) {
      output.writeUInt64(1, billno_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (billno_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, billno_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.seezoon.stub.billno.GetBillnoResp)) {
      return super.equals(obj);
    }
    com.seezoon.stub.billno.GetBillnoResp other = (com.seezoon.stub.billno.GetBillnoResp) obj;

    if (getBillno()
        != other.getBillno()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BILLNO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBillno());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.seezoon.stub.billno.GetBillnoResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.seezoon.stub.billno.GetBillnoResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.seezoon.stub.billno.GetBillnoResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.seezoon.stub.billno.GetBillnoResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.seezoon.billno.GetBillnoResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.seezoon.billno.GetBillnoResp)
      com.seezoon.stub.billno.GetBillnoRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seezoon.stub.billno.BillnoOuterClass.internal_static_com_seezoon_billno_GetBillnoResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seezoon.stub.billno.BillnoOuterClass.internal_static_com_seezoon_billno_GetBillnoResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seezoon.stub.billno.GetBillnoResp.class, com.seezoon.stub.billno.GetBillnoResp.Builder.class);
    }

    // Construct using com.seezoon.stub.billno.GetBillnoResp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      billno_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.seezoon.stub.billno.BillnoOuterClass.internal_static_com_seezoon_billno_GetBillnoResp_descriptor;
    }

    @java.lang.Override
    public com.seezoon.stub.billno.GetBillnoResp getDefaultInstanceForType() {
      return com.seezoon.stub.billno.GetBillnoResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.seezoon.stub.billno.GetBillnoResp build() {
      com.seezoon.stub.billno.GetBillnoResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.seezoon.stub.billno.GetBillnoResp buildPartial() {
      com.seezoon.stub.billno.GetBillnoResp result = new com.seezoon.stub.billno.GetBillnoResp(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.seezoon.stub.billno.GetBillnoResp result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.billno_ = billno_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.seezoon.stub.billno.GetBillnoResp) {
        return mergeFrom((com.seezoon.stub.billno.GetBillnoResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.seezoon.stub.billno.GetBillnoResp other) {
      if (other == com.seezoon.stub.billno.GetBillnoResp.getDefaultInstance()) return this;
      if (other.getBillno() != 0L) {
        setBillno(other.getBillno());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              billno_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long billno_ ;
    /**
     * <code>uint64 billno = 1;</code>
     * @return The billno.
     */
    @java.lang.Override
    public long getBillno() {
      return billno_;
    }
    /**
     * <code>uint64 billno = 1;</code>
     * @param value The billno to set.
     * @return This builder for chaining.
     */
    public Builder setBillno(long value) {

      billno_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 billno = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBillno() {
      bitField0_ = (bitField0_ & ~0x00000001);
      billno_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.seezoon.billno.GetBillnoResp)
  }

  // @@protoc_insertion_point(class_scope:com.seezoon.billno.GetBillnoResp)
  private static final com.seezoon.stub.billno.GetBillnoResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.seezoon.stub.billno.GetBillnoResp();
  }

  public static com.seezoon.stub.billno.GetBillnoResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetBillnoResp>
      PARSER = new com.google.protobuf.AbstractParser<GetBillnoResp>() {
    @java.lang.Override
    public GetBillnoResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetBillnoResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetBillnoResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.seezoon.stub.billno.GetBillnoResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

