// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: billno.proto

package com.seezoon.stub.billno;


/**
* Validates {@code GetBillnoResp} protobuf objects.
*/
@SuppressWarnings("all")
public class GetBillnoRespValidator implements io.envoyproxy.pgv.ValidatorImpl<com.seezoon.stub.billno.GetBillnoResp>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.seezoon.stub.billno.GetBillnoResp.class)) return new GetBillnoRespValidator();
		
		return null;
	}
		
	
	
	

	public void assertValid(com.seezoon.stub.billno.GetBillnoResp proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Billno

	
	
	}

}

