// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billno.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.billno;

public interface GetBillnoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.seezoon.billno.GetBillnoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string biz_code = 1 [(.validate.rules) = { ... }</code>
   * @return The bizCode.
   */
  java.lang.String getBizCode();
  /**
   * <code>string biz_code = 1 [(.validate.rules) = { ... }</code>
   * @return The bytes for bizCode.
   */
  com.google.protobuf.ByteString
      getBizCodeBytes();
}
