// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billno.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.billno;

public interface GetBillnoRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.seezoon.billno.GetBillnoResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 billno = 1;</code>
   * @return The billno.
   */
  long getBillno();
}
