// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: billno.proto

package com.seezoon.stub.billno;


/**
* Validates {@code GetBillnoReq} protobuf objects.
*/
@SuppressWarnings("all")
public class GetBillnoReqValidator implements io.envoyproxy.pgv.ValidatorImpl<com.seezoon.stub.billno.GetBillnoReq>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.seezoon.stub.billno.GetBillnoReq.class)) return new GetBillnoReqValidator();
		
		return null;
	}
		
	
	
	

	public void assertValid(com.seezoon.stub.billno.GetBillnoReq proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.StringValidation.minLength(".com.seezoon.billno.GetBillnoReq.biz_code", proto.getBizCode(), 1);
	
	
	}

}

